-----BEGIN PRIVATE KEY-----
MIGTAgEAMBMGByqGSM49AgEGCCqGSM49AwEHBHkwdwIBAQQgnMFSDGtysukwsPv1
s6ZYSlRkPpRuDNHvAhrMvHDH0JmgCgYIKoZIzj0DAQehRANCAAT5DVUZmAxYNYrL
pZVapwSdQ6tsWynTKP3YUaW2YX0+WmCnDFxgF4krqRprjYAJ9NHNI8g0903gxQMB
g4GeuNYV
-----END PRIVATE KEY-----